apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aharf4tol-go 
  janus-idp.io/tekton: aharf4tol-go
  backstage.io/kubernetes-id: aharf4tol-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aharf4tol-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml